Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -35,9 +35,19 @@ jobs:
       run: |
         brew install tiger-vnc
 
+    - name: Find vncserver Path
+      id: find_vncserver
+      run: |
+        which vncserver
+
     - name: Start VNC Server
       run: |
-        vncserver :1 -geometry 1920x1080 -depth 24
+        vncserver_path=$(which vncserver)
+        if [ -z "$vncserver_path" ]; then
+          echo "vncserver command not found"
+          exit 1
+        fi
+        $vncserver_path :1 -geometry 1920x1080 -depth 24
 
     - name: Configure VNC Password
       run: |
